import localFont from "next/font/local";
import { ContextProvider } from "@/context/context";
import { AuthContextProvider } from "@/context/userContext";
import "./globals.css";

const urbanist = localFont({
  src: "../../public/fonts/urbanist/Urbanist-VariableFont_wght.ttf",
  variable: "--font-urbanist",
  weight: "100 900",
});
const urbanistItalic = localFont({
  src: "../../public/fonts/urbanist/Urbanist-Italic-VariableFont_wght.ttf",
  variable: "--font-urbanist-italic",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <ContextProvider>
          <body
            className={`${urbanist.variable} ${urbanistItalic.variable} antialiased`}
          >
            {children}
          </body>
        </ContextProvider>
      </AuthContextProvider>
    </html>
  );
}
