import { ContextProvider } from "@/context/context";
import { AuthContextProvider } from "@/context/userContext";
import ClientLayout from "./clientLayout";
import "./globals.css";
import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <AuthContextProvider>
            <ContextProvider>
              <ClientLayout>{children}</ClientLayout>
            </ContextProvider>
          </AuthContextProvider>
        </Suspense>
      </body>
    </html>
  );
}
