import { ContextProvider } from "@/context/context";
import { AuthContextProvider } from "@/context/userContext";
import ClientLayout from "./clientLayout";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <ContextProvider>
          <ClientLayout>{children}</ClientLayout>
        </ContextProvider>
      </AuthContextProvider>
    </html>
  );
}
